config/routes.rb
RailsStore::Application.routes.draw do
  # resources :reviews
  # resources :products

  root :to => 'products#index'

  get '/reviews/:id' => 'reviews#show'
  get '/reviews' => 'reviews#index'
  get '/reviews/new(.:format)' => 'reviews#new'

  get '/products/:id' => 'products#show'
  get '/products' => 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :description, :image_url

  has_many :reviews

  validates_uniqueness_of :name
  validates_presence_of :name, :price
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :body, :product_id, :rating
  belongs_to :product

  validates_length_of :body, :within => 50...1000
  validates_inclusion_of :rating, :in => 0..5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @products = Product.all
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    product_id = params[:id]
    @product = Product.find(product_id) if product_id
    @reviews = Review.where(:product_id => product_id) if product_id

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new
    # @products = Product.all

    @product = Product.find(params[:product_id]) if params[:product_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsStore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h3>Products</h3>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Reviews</th>
    <th>Description</th>
    <th>Image</th>
    <th>Detail</th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= number_to_currency(product.price / 100.0) %></td>
    <td><a href='/reviews/<%= product.id %>'>Reviews</a></td>
    <td><%= product.description %></td>
    <td><img src="<%= product.image_url %>" alt="Image for <%= product.name%>" ></td>
    <td><a href='/products/?=:product_id=<%= product.id %>'>Detail</a></td>
  </tr>
<% end %>
</table>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= number_to_currency(@product.price / 100) %>
</p>

<p>

</p>
<form action="/reviews/new" method="get">
  <input type="hidden" value="<%= @product.id %>" name="product_id">
    <button type="submit">Write a review for <%= @product.name %></button>
</form>

<a href="/products">Back</a>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <% if @product.nil? %>
    <select name="review[product_id]">
      <% @products.each do |product| %>
        <option value="<%= product.id %>">
          <%= product.name %>
        </option>
      <% end %>
    </select>
    <% else %>
      <input type="hidden" name='review[product_id]' value='<%= @product.id %>'
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Body</th>
    <th>Rating</th>
    <th>Product</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.body %></td>
    <td><%= review.rating %></td>
    <td><%= review.product_id %></td>
    <td><%= link_to 'Show', review %></td>
    <td><%= link_to 'Edit', edit_review_path(review) %></td>
    <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h2>New review of <%= @product.name %></h2>


<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<% if @reviews.size == 0 %>
  <p>
    No reviews for <%= @product.name %>.
  </p>

<% else %> 
<h2>Reviews for <%= @product.name %></h2>
  <table>
    <tr>
      <th>Rating</th>
      <th>Body</th>
    </tr>
    <% @reviews.each do |review| %>
      <tr>
        <td>
          <%= review.rating %>
        </td>
        <td>
          <%= review.body %>
        </td>
      </tr>
    <% end %> 
  </table>
 <% end %> 

<%= link_to 'Back', reviews_path %>